version: '3'
services:
  api:
    # restart service when service fail
    restart: always
    # build Dockerfile in folder /api
    build: ./api
    # map port local port:container port
    ports:
      - '5050:80'
    volumes:
      - ./api:/app
  db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    #    environment:
    #      MONGO_INITDB_ROOT_USERNAME: root
    #      MONGO_INITDB_ROOT_PASSWORD: very-strong-db-password
    volumes:
      # if use - mongodb_data: it will map mongodb_data in linux of docker
      # if use - ./mongodb_data: it will map mongodb_data in windown which is host of docker
      - mongodb_data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      # server are [mongo:] above
      ME_CONFIG_MONGODB_SERVER: db
    #      ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #      ME_CONFIG_MONGODB_ADMINPASSWORD: very-strong-db-password
    depends_on:
      # it will start mongo-express when mongo start only
      - db
# create mongodb_data volume inside linux of docker [docker is linux vm build on windown]
volumes:
  mongodb_data:
